import { PrismaClient, Role, VehicleStatus } from "@prisma/client";
import bcrypt from "bcryptjs";

const db = new PrismaClient();

async function main() {
  const adminHash = await bcrypt.hash("Admin123!", 12);
  const userHash = await bcrypt.hash("User123!", 12);

  await db.user.upsert({
    where: { email: "admin@coolcars.pl" },
    update: {},
    create: { name: "Administrator", email: "admin@coolcars.pl", passwordHash: adminHash, role: Role.ADMIN },
  });

  await db.user.upsert({
    where: { email: "klient@coolcars.pl" },
    update: {},
    create: { name: "Jan Kowalski", email: "klient@coolcars.pl", passwordHash: userHash, role: Role.USER },
  });

  const vehicles = [
    {
      slug: "iveco-daily-35c14-chlodnia-2021",
      stockNumber: "MV-601",
      title: "Iveco Daily 35C14 Chłodnia / Carrier Xarios 350",
      brand: "Iveco",
      model: "Daily 35C14",
      year: 2021,
      mileage: 168400,
      priceNet: 89900,
      vatRate: 23,
      category: "Samochody dostawcze",
      fuel: "Diesel",
      transmission: "Manualna",
      powerHp: 136,
      engineCapacity: 2287,
      dmc: 3500,
      payload: 760,
      location: "Warszawa",
      description: "Sprawdzony samochód chłodniczy po pełnym przeglądzie. Agregat Carrier, komplet dokumentów, gotowy do pracy od pierwszego dnia.",
      status: VehicleStatus.AVAILABLE,
      featured: true,
      image: "/vehicles/truck-1.svg",
    },
    {
      slug: "renault-master-kontener-winda-2020",
      stockNumber: "MV-618",
      title: "Renault Master Kontener / Winda Dhollandia",
      brand: "Renault",
      model: "Master",
      year: 2020,
      mileage: 214900,
      priceNet: 74900,
      vatRate: 23,
      category: "Samochody dostawcze",
      fuel: "Diesel",
      transmission: "Manualna",
      powerHp: 165,
      engineCapacity: 2299,
      dmc: 3500,
      payload: 820,
      location: "Łódź",
      description: "Praktyczny kontener z windą załadowczą. Regularnie serwisowany, bardzo dobry stan techniczny i wizualny, przygotowany do odbioru.",
      status: VehicleStatus.AVAILABLE,
      featured: true,
      image: "/vehicles/truck-2.svg",
    },
    {
      slug: "mercedes-atego-1224-chlodnia-2019",
      stockNumber: "MV-627",
      title: "Mercedes-Benz Atego 1224 Chłodnia / Thermo King",
      brand: "Mercedes-Benz",
      model: "Atego 1224",
      year: 2019,
      mileage: 328500,
      priceNet: 159900,
      vatRate: 23,
      category: "Ciężarówki > 3,5 t",
      fuel: "Diesel",
      transmission: "Automatyczna",
      powerHp: 238,
      engineCapacity: 7698,
      dmc: 11990,
      payload: 4700,
      location: "Poznań",
      description: "Ciężarówka chłodnicza z agregatem Thermo King i windą. Pełna historia serwisowa, kabina dzienna, zabudowa w bardzo dobrym stanie.",
      status: VehicleStatus.AVAILABLE,
      featured: true,
      image: "/vehicles/truck-3.svg",
    },
    {
      slug: "fiat-ducato-l4h2-2022",
      stockNumber: "MV-634",
      title: "Fiat Ducato L4H2 2.2 MultiJet / Kamera / LED",
      brand: "Fiat",
      model: "Ducato L4H2",
      year: 2022,
      mileage: 88200,
      priceNet: 84900,
      vatRate: 23,
      category: "Furgony",
      fuel: "Diesel",
      transmission: "Manualna",
      powerHp: 140,
      engineCapacity: 2184,
      dmc: 3500,
      payload: 1180,
      location: "Katowice",
      description: "Długi i wysoki furgon w bardzo dobrym stanie. Kamera cofania, klimatyzacja, światła LED oraz komplet dokumentacji serwisowej.",
      status: VehicleStatus.RESERVED,
      featured: false,
      image: "/vehicles/van-1.svg",
    },
    {
      slug: "volvo-fl-280-izoterma-2020",
      stockNumber: "MV-641",
      title: "Volvo FL 280 Izoterma / Winda 1500 kg",
      brand: "Volvo",
      model: "FL 280",
      year: 2020,
      mileage: 276100,
      priceNet: 179900,
      vatRate: 23,
      category: "Ciężarówki > 3,5 t",
      fuel: "Diesel",
      transmission: "Automatyczna",
      powerHp: 280,
      engineCapacity: 7698,
      dmc: 16000,
      payload: 7100,
      location: "Wrocław",
      description: "Volvo FL w zabudowie izotermicznej, winda 1500 kg, automatyczna skrzynia i komfortowa kabina. Samochód po przeglądzie sprzedażowym.",
      status: VehicleStatus.AVAILABLE,
      featured: false,
      image: "/vehicles/truck-4.svg",
    },
    {
      slug: "toyota-corolla-hybrid-2023",
      stockNumber: "MV-649",
      title: "Toyota Corolla 1.8 Hybrid Comfort / Salon PL",
      brand: "Toyota",
      model: "Corolla",
      year: 2023,
      mileage: 24600,
      priceNet: 95900,
      vatRate: 23,
      category: "Samochody osobowe",
      fuel: "Hybryda",
      transmission: "Automatyczna",
      powerHp: 140,
      engineCapacity: 1798,
      dmc: 1835,
      payload: 455,
      location: "Warszawa",
      description: "Polski salon, pierwszy właściciel, pełna historia ASO. Bogata wersja Comfort z pakietem bezpieczeństwa i adaptacyjnym tempomatem.",
      status: VehicleStatus.AVAILABLE,
      featured: false,
      image: "/vehicles/car-1.svg",
    },
  ];

  for (const vehicle of vehicles) {
    await db.vehicle.upsert({ where: { stockNumber: vehicle.stockNumber }, update: vehicle, create: vehicle });
  }
}

main().finally(() => db.$disconnect());
