"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

type V = {
 id?:string; title:string; brand:string; model:string; year:number; mileage:number; priceNet:number; vatRate:number; stockNumber:string; category:string; fuel:string; transmission:string; powerHp:number|null; engineCapacity:number|null; dmc:number|null; payload:number|null; location:string; description:string; status:'AVAILABLE'|'RESERVED'|'SOLD'|'DRAFT'; featured:boolean; image:string;
};
const defaults:V={title:'',brand:'',model:'',year:new Date().getFullYear(),mileage:0,priceNet:0,vatRate:23,stockNumber:'',category:'Samochody dostawcze',fuel:'Diesel',transmission:'Manualna',powerHp:null,engineCapacity:null,dmc:null,payload:null,location:'Warszawa',description:'',status:'AVAILABLE',featured:false,image:'/vehicles/truck-1.svg'};
export function VehicleForm({vehicle}:{vehicle?:V}){const data=vehicle??defaults;const router=useRouter();const [error,setError]=useState('');const [loading,setLoading]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');const fd=new FormData(e.currentTarget);const nullable=(k:string)=>{const v=String(fd.get(k)||'').trim();return v?Number(v):null};const payload={title:fd.get('title'),brand:fd.get('brand'),model:fd.get('model'),year:Number(fd.get('year')),mileage:Number(fd.get('mileage')),priceNet:Number(fd.get('priceNet')),vatRate:Number(fd.get('vatRate')),stockNumber:fd.get('stockNumber'),category:fd.get('category'),fuel:fd.get('fuel'),transmission:fd.get('transmission'),powerHp:nullable('powerHp'),engineCapacity:nullable('engineCapacity'),dmc:nullable('dmc'),payload:nullable('payload'),location:fd.get('location'),description:fd.get('description'),status:fd.get('status'),featured:fd.get('featured')==='on',image:fd.get('image')};const url=vehicle?.id?`/api/admin/vehicles/${vehicle.id}`:'/api/admin/vehicles';const r=await fetch(url,{method:vehicle?.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));setLoading(false);if(!r.ok){setError(j.error||'Nie udało się zapisać');return;}router.push('/admin/pojazdy');router.refresh();}
 const f=(label:string,name:keyof V,type='text',extra:any={})=><div className="field"><label>{label}</label><input className="input" name={name} type={type} defaultValue={(data[name]??'') as any} {...extra}/></div>;
 return <form className="admin-form" onSubmit={submit}><div className="form-grid">
  <div className="full">{f('Tytuł oferty','title','text',{required:true})}</div>{f('Marka','brand','text',{required:true})}{f('Model','model','text',{required:true})}{f('Rok produkcji','year','number',{required:true,min:1980})}{f('Przebieg (km)','mileage','number',{required:true,min:0})}{f('Cena netto (PLN)','priceNet','number',{required:true,min:0})}{f('VAT (%)','vatRate','number',{required:true,min:0})}{f('Numer oferty','stockNumber','text',{required:true})}
  <div className="field"><label>Kategoria</label><select className="select" name="category" defaultValue={data.category}><option>Samochody dostawcze</option><option>Ciężarówki &gt; 3,5 t</option><option>Furgony</option><option>Samochody osobowe</option><option>Kontenery chłodnicze</option></select></div>
  <div className="field"><label>Paliwo</label><select className="select" name="fuel" defaultValue={data.fuel}><option>Diesel</option><option>Benzyna</option><option>Hybryda</option><option>Elektryczny</option><option>CNG</option></select></div>
  <div className="field"><label>Skrzynia</label><select className="select" name="transmission" defaultValue={data.transmission}><option>Manualna</option><option>Automatyczna</option></select></div>
  {f('Moc (KM)','powerHp','number',{min:0})}{f('Pojemność (cm³)','engineCapacity','number',{min:0})}{f('DMC (kg)','dmc','number',{min:0})}{f('Ładowność (kg)','payload','number',{min:0})}{f('Lokalizacja','location','text',{required:true})}
  <div className="field"><label>Status</label><select className="select" name="status" defaultValue={data.status}><option value="AVAILABLE">Dostępny</option><option value="RESERVED">Rezerwacja</option><option value="SOLD">Sprzedany</option><option value="DRAFT">Szkic</option></select></div>
  <div className="full">{f('Ścieżka / URL zdjęcia','image','text',{required:true})}</div>
  <div className="field full"><label>Opis</label><textarea className="textarea" name="description" defaultValue={data.description} required minLength={20}/></div>
  <label className="check full"><input type="checkbox" name="featured" defaultChecked={data.featured}/> Pokaż jako ofertę polecaną na stronie głównej</label>
 </div>{error&&<div className="form-error">{error}</div>}<div style={{display:'flex',gap:10,marginTop:20}}><button className="btn btn-accent" disabled={loading}>{loading?'Zapisywanie...':'Zapisz pojazd'}</button><button className="btn btn-ghost" type="button" onClick={()=>router.back()}>Anuluj</button></div></form>}
